services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_net

  bluehorseshoe:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bluehorseshoe
    container_name: bluehorseshoe
    ports:
      - "8001:80"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      ALPHAVANTAGE_KEY: ${ALPHAVANTAGE_KEY}
      ALPHAVANTAGE_CPS: ${ALPHAVANTAGE_CPS:-5}
    depends_on:
      - mongo
      - redis
    networks:
      - app_net
    volumes:
      # Mount the src folder from host into the container
      - ..:/workspaces/BlueHorseshoe

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bluehorseshoe
    container_name: bluehorseshoe_worker
    command: celery -A bluehorseshoe.api.celery_app worker --loglevel=info
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      ALPHAVANTAGE_KEY: ${ALPHAVANTAGE_KEY}
      ALPHAVANTAGE_CPS: ${ALPHAVANTAGE_CPS:-5}
      PYTHONPATH: /workspaces/BlueHorseshoe/src
    depends_on:
      - mongo
      - redis
    networks:
      - app_net
    volumes:
      - ..:/workspaces/BlueHorseshoe

networks:
  app_net:

volumes:
  mongo_data: