services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net

  bluehorseshoe:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bluehorseshoe
    container_name: bluehorseshoe
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      ALPHAVANTAGE_KEY: ${ALPHAVANTAGE_KEY}
      ALPHAVANTAGE_CPS: 2
      SMTP_SERVER: ${SMTP_SERVER:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
      EMAIL_SENDER: ${EMAIL_SENDER}
    depends_on:
      - mongo
    networks:
      - app_net
    volumes:
      # Mount the src folder from host into the container
      - ..:/workspaces/BlueHorseshoe

networks:
  app_net:

volumes:
  mongo_data:
